
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 09 17:38:58 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int b = 3;
  public static final int a = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

