
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 11 19:28:53 CEST 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Usuario = 6;
  public static final int Digito = 11;
  public static final int Destino = 9;
  public static final int Origen = 8;
  public static final int EOF = 0;
  public static final int Password = 7;
  public static final int PuntoyComa = 3;
  public static final int error = 1;
  public static final int Guion = 5;
  public static final int Participantes = 2;
  public static final int Vinculos = 4;
  public static final int NombreRed = 10;
}

